# This python script pulls the data generated by running: SURION_mAP.sh --> darknet_data_extract.sh
import os
from pprint import pprint
src = '/home/ryzen1/Surion/training/yolov4_Surion_OI_2/extracted_results.txt'

file = open(src, 'r')
inc = 2500
data_dict = {}
for it in range(inc, 100000+inc, inc):
    line0 = file.readline().strip()
    if line0.split(' ')[0] == 'class_id':
        break
    iteration = int(line0.split('.')[0])
    if(iteration not in data_dict.keys()):
        block = []
        linen = file.readline().strip()
        while (linen!='##########################################################'):
            block.append(linen)
            linen = file.readline().strip()
        data_dict[iteration] = {'block':block}

file.close()
# pprint(data_dict)

for key in data_dict.keys():
    for element in data_dict[key]['block']:
        if(element=='--'):
            data_dict[key]['block'].remove('--')
    print(key)
    pprint(data_dict[key]['block'])

for it in range(inc, 100000, inc):
    if(it not in data_dict.keys()):
        print(it)
